"use client";

import LogoClient from "./_components/LogoCliente";
import { useTranslations } from "next-intl";

export default function Clients() {
  const t = useTranslations("Index");

  return (
    <section id="nossos-clientes" className="section nossos-clientes">
      <div className="container">
        <h2 className="title">{t("titleClients")}</h2>
        <div className="row justify-content-center">
          <div className="col-md-12">
            <div className="box-logos-clientes hidden-mobile">
              <ul>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_americanas_pb.png"
                    imageOver="/assets/images/clientes_americanas.png"
                    alt="Americanas"
                    width={164}
                    height={38}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_mondelez_pb.png"
                    imageOver="/assets/images/clientes_mondelez.png"
                    alt="Mondelez"
                    width={126}
                    height={50}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_ovomaltine_pb.png"
                    imageOver="/assets/images/clientes_ovomaltine.png"
                    alt="Ovomaltine"
                    width={79}
                    height={66}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_bauduco_logo_pb.png"
                    imageOver="/assets/images/clientes_bauduco_logo.png"
                    alt="Bauduco"
                    width={105}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_goldko_pb.png"
                    imageOver="/assets/images/clientes_goldko.png"
                    alt="Goldko"
                    width={114}
                    height={40}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_casa_bauduco_pb.png"
                    imageOver="/assets/images/clientes_casa_bauduco.png"
                    alt="Casa Bauduco"
                    width={80}
                    height={80}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_nestle_logo_pb.png"
                    imageOver="/assets/images/clientes_nestle_logo.png"
                    alt="Nestle"
                    width={107}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_lindt_pb.png"
                    imageOver="/assets/images/clientes_lindt_rgb.png"
                    alt="Lindt"
                    width={135}
                    height={56}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_neugebauer_pb.png"
                    imageOver="/assets/images/clientes_neugebauer.png"
                    alt="Neugebauer"
                    width={135}
                    height={56}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_dengo_pb.png"
                    imageOver="/assets/images/clientes_dengo_rgb.png"
                    alt="Dengo"
                    width={65}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/cliente_havana_pb.png"
                    imageOver="/assets/images/cliente_havana_rgb.png"
                    alt="Havana"
                    width={160}
                    height={46}
                  />
                </li>
              </ul>
            </div>

            <div className="box-logos-clientes hidden-desktop">
              <ul>
              <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_americanas.png"
                    alt="Americanas"
                    width={164}
                    height={38}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_mondelez.png"
                    alt="Mondelez"
                    width={126}
                    height={50}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_ovomaltine.png"
                    alt="Ovomaltine"
                    width={79}
                    height={66}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_bauduco_logo.png"
                    alt="Bauduco"
                    width={105}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_goldko.png"
                    alt="Goldko"
                    width={114}
                    height={40}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_casa_bauduco.png"
                    alt="Casa Bauduco"
                    width={80}
                    height={80}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_nestle_logo.png"
                    alt="Nestle"
                    width={107}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_lindt_rgb.png"
                    alt="Lindt"
                    width={135}
                    height={56}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_neugebauer.png"
                    alt="Neugebauer"
                    width={135}
                    height={56}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/clientes_dengo_rgb.png"
                    imageOver="/assets/images/clientes_dengo_rgb.png"
                    alt="Dengo"
                    width={65}
                    height={60}
                  />
                </li>
                <li>
                  <LogoClient
                    defaultImage="/assets/images/cliente_havana_rgb.png"
                    imageOver="/assets/images/cliente_havana_rgb.png"
                    alt="Havana"
                    width={160}
                    height={46}
                  />
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
